# Oh My Posh 설정
$env:Path += ";$env:LOCALAPPDATA\Programs\oh-my-posh\bin"
oh-my-posh init pwsh --config "$([Environment]::GetFolderPath('MyDocuments'))\PowerShell\illusi0n-dayfox.omp.json" | Invoke-Expression

# Dayfox 라이트 배경용 PSReadLine 색상 (기본값은 다크 배경용이라 밝은 배경에서 안 보임)
if (Get-Module PSReadLine) {
    $e = [char]27
    Set-PSReadLineOption -Colors @{
        Command                = '#2848a9'
        Parameter              = '#534c45'
        Operator               = '#3d2b5a'
        Variable               = '#287980'
        String                 = '#396847'
        Number                 = '#ac5402'
        Type                   = '#6e33ce'
        Keyword                = '#6e33ce'
        Member                 = '#b86e28'
        Comment                = '#837a72'
        Default                = '#3d2b5a'
        Error                  = '#a5222f'
        Emphasis               = "$e[1;38;2;172;84;2m"
        InlinePrediction       = '#a39a8d'
        ListPrediction         = '#577f63'
        Selection              = "$e[38;2;61;43;90;48;2;231;210;190m"
        ListPredictionSelected = "$e[48;2;231;210;190m"
    }
}

# ls(Get-ChildItem) 파일 목록 색상: 기본값이 폴더에 파란 '배경'을 깔아서 형광펜처럼 보임 → 글자색만 사용
$e = [char]27
$PSStyle.FileInfo.Directory    = "$e[1;38;2;40;72;169m"   # 폴더: 굵은 파랑 (Dayfox blue)
$PSStyle.FileInfo.SymbolicLink = "$e[38;2;40;121;128m"    # 심볼릭 링크: 청록
$PSStyle.FileInfo.Executable   = "$e[38;2;57;104;71m"     # 실행 파일: 초록

function ppe {
    Set-Location "$env:APPDATA\pyRevit\Extensions"
}

function root {
    Set-Location C:\
}

function e {
    Set-Location E:\
}

function rhino {
    Start-Process "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Rhino 8\Rhino 8.lnk"
}

function revit {
    Start-Process "C:\Program Files\Autodesk\Revit 2024\Revit.exe"
}

function acad {
    Start-Process "C:\Program Files\Autodesk\AutoCAD 2023\acad.exe"
}

function boj {
    Set-Location "$env:USERPROFILE\boj"
    nvim
}

function env_path {
    param(
        [string]$NewPath
    )

    if (-not (Test-Path $NewPath)) {
        Write-Host "경로가 존재하지 않습니다: $NewPath"
        return
    }

    $currentPath = [Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::Machine)

    if ($currentPath -like "*$NewPath*") {
        Write-Host "이미 시스템 PATH에 존재합니다: $NewPath"
    }
    else {
        [Environment]::SetEnvironmentVariable(
            "Path",
            $currentPath + ";$NewPath",
            [EnvironmentVariableTarget]::Machine
        )
        Write-Host "시스템 PATH에 추가 완료: $NewPath"
    }
}

function gh_venv {
    if ($env:VIRTUAL_ENV) {
        deactivate
    }
    else {
        & "$env:USERPROFILE\grasshopper\Scripts\Activate.ps1"
    }
}

$env:Path += ";$env:APPDATA\npm"
# >>> intelligent-terminal shell-integration >>>
# Auto-generated by Intelligent Terminal. Do not edit between markers.
# Documents is resolved at runtime so this survives OneDrive Known
# Folder Move and is a silent no-op on machines without IT installed.
$__it_si = Join-Path ([Environment]::GetFolderPath('MyDocuments')) 'PowerShell\shell-integration_v2.ps1'
if (Test-Path -LiteralPath $__it_si) { . $__it_si }
Remove-Variable __it_si -ErrorAction SilentlyContinue
# <<< intelligent-terminal shell-integration <<<
